[build]
  publish = "dist"
  command = ""

[[redirects]]
  from = "/ipsum"
  to = "/.netlify/functions/jason-ipsum"
  status = 200

[[redirects]]
  from = "/ipsum/:quantity"
  to = "/.netlify/functions/jason-ipsum?quantity=:quantity"
  status = 200
